[package]
name = "libmotoc"
version = "0.3.6"
edition = "2021"
description = "Monado Tracking Origin Calibrator library"

[dependencies]
indicatif.workspace = true
libmonado.workspace = true
log.workspace = true
nalgebra.workspace = true
openxr.workspace = true
openxr_mndx_xdev_space.workspace = true

colored = "3.1.1"
mint = { version = "0.5", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
xdg = "3.0.0"

[build-dependencies]
bindgen = "0.72.1"
