[workspace]
resolver = "2"
members = ["libmotoc", "motoc"]

[workspace.dependencies]
indicatif = "0.18"
libmonado = "1.6"
log = "0.4"
nalgebra = { version = "0.34", features = ["mint", "serde-serialize"] }
openxr = { version = "0.21", features = ["linked", "mint"], default-features = false }
openxr_mndx_xdev_space = "0.2.0"
