[package]
name = "motoc"
version = "0.3.6"
edition = "2021"
description = "Monado Tracking Origin Calibrator"

[dependencies]
libmotoc = { path = "../libmotoc" }

anyhow = "1.0"
indicatif.workspace = true
libmonado.workspace = true
log.workspace = true
nalgebra.workspace = true
openxr.workspace = true
openxr_mndx_xdev_space.workspace = true

clap = { version = "4.5", features = ["derive"] }
ctrlc = { version = "3.5", features = ["termination"] }
env_logger = "0.11"
