name: Check Build

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9
    - name: Prepare Environment
      run: |
        sudo apt install libopenxr-dev
        rustup update stable
    - name: Build
      run: cargo build --verbose

